import { all, get, run, jsonOrNull } from "../db.ts";
import { codexJson } from "../ai/codex.ts";
import { briefPrompt, type BriefEvidenceInput } from "../ai/prompts.ts";
import { ZBrief, JBrief, type Brief } from "../ai/schemas.ts";
import { nowSec, truncate } from "../lib/text.ts";
import type { AppSettings } from "../settings.ts";
import type { JudgeVerdict } from "../ai/schemas.ts";

interface ClusterRow {
  id: number;
  scan_id: number;
  name: string;
  summary: string | null;
  voices: number;
  distinct_authors: number;
  platform_list_json: string | null;
  judge_json: string | null;
  demand_score: number;
}

function marketContextFor(scanId: number): string[] {
  const out: string[] = [];
  const marketItems = all<{ source: string; title: string; body: string }>(
    `SELECT source, title, body FROM items WHERE scan_id=? AND meta_json LIKE '%"kind":"market"%' LIMIT 14`,
    scanId
  );
  for (const m of marketItems) {
    const label = m.source === "g2" ? "G2 category leader" : "Product Hunt launch";
    out.push(`${label}: ${m.title} — ${truncate(m.body, 100)}`);
  }
  const apps = all<{ meta_json: string; n: number }>(
    `SELECT meta_json, COUNT(*) AS n FROM items
     WHERE scan_id=? AND source IN ('playstore','appstore') AND meta_json IS NOT NULL
     GROUP BY json_extract(meta_json, '$.appTitle') LIMIT 8`,
    scanId
  );
  for (const a of apps) {
    const meta = jsonOrNull<{ appTitle?: string }>(a.meta_json);
    if (meta?.appTitle) out.push(`Existing app: ${meta.appTitle} (${a.n} low-star reviews mined)`);
  }
  return out;
}

function evidenceForBrief(clusterId: number): BriefEvidenceInput[] {
  return all<{
    source: string;
    title: string;
    quote: string | null;
    score: number;
    comments: number;
    url: string;
  }>(
    `SELECT DISTINCT i.source, i.title, p.quote, i.score, i.comments, i.url
     FROM cluster_problems cp JOIN problems p ON p.id=cp.problem_id JOIN items i ON i.id=p.item_id
     WHERE cp.cluster_id=? ORDER BY (i.score+i.comments) DESC LIMIT 10`,
    clusterId
  ).map((r) => ({
    source: r.source,
    title: truncate(r.title, 120),
    quote: truncate(r.quote ?? "", 200),
    engagement: r.score + r.comments,
    url: r.url,
  }));
}

export function renderBriefMd(brief: Brief, cluster: ClusterRow, evidence: BriefEvidenceInput[]): string {
  const platforms = jsonOrNull<string[]>(cluster.platform_list_json) ?? [];
  const lines: string[] = [
    `# ${brief.title}`,
    ``,
    `> ${brief.oneLiner}`,
    ``,
    `**Validated problem:** ${cluster.name}  `,
    `**Demand evidence:** ~${cluster.voices.toLocaleString()} voices · ${cluster.distinct_authors} distinct complainers · ${platforms.length} platforms (${platforms.join(", ")}) · demand score ${cluster.demand_score}/100`,
    ``,
    `## Problem`,
    brief.problem,
    ``,
    `## Target user`,
    brief.targetUser,
    ``,
    `## MVP (4–6 weeks)`,
    ...brief.mvpFeatures.map((f, i) => `${i + 1}. ${f}`),
    ``,
    `## Differentiation`,
    brief.differentiation,
    ``,
    `## Monetization`,
    brief.monetization,
    ``,
    `## Go-to-market (first 100 customers)`,
    ...brief.gtm.map((g) => `- ${g}`),
    ``,
    `## Competition`,
    ...(brief.competitors.length
      ? brief.competitors.map((c) => `- **${c.name}** — ${c.note}`)
      : ["- No direct competitors visible in the harvested evidence."]),
    ``,
    `## Risks`,
    ...brief.risks.map((r) => `- ${r}`),
    ``,
    `## Why now`,
    brief.whyNow || "—",
    ``,
    `## 90-day success metrics`,
    ...brief.successMetrics.map((m) => `- ${m}`),
    ``,
    `## Evidence trail`,
    ...evidence.map(
      (e) => `- [${e.source}] "${e.quote || e.title}" (${e.engagement} engagement) — ${e.url}`
    ),
    ``,
    `---`,
    `*Generated by Lodestone from real harvested evidence. Every quote above links to its source.*`,
  ];
  return lines.join("\n");
}

export async function generateBrief(
  clusterId: number,
  settings: AppSettings,
  signal: AbortSignal | undefined,
  steer?: string
): Promise<{ id: number; title: string }> {
  const cluster = get<ClusterRow>(
    `SELECT id, scan_id, name, summary, voices, distinct_authors, platform_list_json, judge_json, demand_score
     FROM clusters WHERE id=?`,
    clusterId
  );
  if (!cluster) throw new Error(`cluster ${clusterId} not found`);
  if (!settings.ai.enabled) throw new Error("AI engine is disabled in Settings — briefs require it");

  const judge = jsonOrNull<JudgeVerdict>(cluster.judge_json) ?? {
    painIntensity: 5,
    wtpEvidence: 3,
    verdict: "validated" as const,
    reasons: [],
    buyerPersona: "",
    competition: "",
    whyNow: "",
  };
  const evidence = evidenceForBrief(clusterId);
  const platforms = jsonOrNull<string[]>(cluster.platform_list_json) ?? [];

  const { data } = await codexJson(
    {
      task: `brief(${cluster.name.slice(0, 30)})`,
      prompt: briefPrompt(
        cluster.name,
        cluster.summary ?? "",
        { buyerPersona: judge.buyerPersona, competition: judge.competition, whyNow: judge.whyNow },
        { voices: cluster.voices, distinctAuthors: cluster.distinct_authors, platforms },
        evidence,
        marketContextFor(cluster.scan_id),
        steer
      ),
      effort: settings.ai.efforts.brief,
      schema: JBrief,
      timeoutMs: 25 * 60_000,
      signal,
    },
    ZBrief
  );

  const md = renderBriefMd(data, cluster, evidence);
  // Replace any previous brief for this cluster.
  run("DELETE FROM opportunities WHERE cluster_id=?", clusterId);
  const { lastId } = run(
    `INSERT INTO opportunities (scan_id, cluster_id, title, one_liner, brief_md, brief_json, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    cluster.scan_id,
    clusterId,
    data.title.slice(0, 160),
    data.oneLiner.slice(0, 300),
    md,
    JSON.stringify(data),
    nowSec()
  );
  return { id: lastId, title: data.title };
}

export async function synthesizeBriefs(
  scanId: number,
  settings: AppSettings,
  signal: AbortSignal | undefined,
  log: (msg: string, type?: "log" | "warn") => void,
  onProgress: (done: number, total: number) => void
): Promise<{ briefs: number }> {
  const top = all<{ id: number; name: string }>(
    `SELECT id, name FROM clusters WHERE scan_id=? AND validated=1 ORDER BY demand_score DESC LIMIT ?`,
    scanId,
    settings.briefsPerScan
  );
  if (top.length === 0) {
    log("no validated clusters — no opportunity briefs to write");
    return { briefs: 0 };
  }
  if (!settings.ai.enabled) {
    log("AI disabled — skipping opportunity briefs (they require the reasoning engine)", "warn");
    return { briefs: 0 };
  }

  let done = 0;
  for (const cluster of top) {
    if (signal?.aborted) throw new Error("aborted");
    try {
      const { title } = await generateBrief(cluster.id, settings, signal);
      done++;
      log(`brief ready: "${title}"`);
      onProgress(done, top.length);
    } catch (err) {
      if (signal?.aborted) throw err;
      log(
        `brief failed for "${cluster.name.slice(0, 40)}" (${err instanceof Error ? err.message.slice(0, 140) : err})`,
        "warn"
      );
      break; // AI likely unavailable — stop instead of hammering
    }
  }
  return { briefs: done };
}
